# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200326
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-net


  chrome:
    image: selenium/node-chrome-debug:3.141.59-20200326
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 36400:5900
    restart: always
    depends_on:
      - selenium-hub
    networks:
      - selenium-net
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1

networks:
  selenium-net:
